#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
#include <bits/stdc++.h>

using namespace std;

// 2つの日がぶつかる時刻T
// T = 1/2 Sigma i=1...N (Ai/Bi)

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    int n;
    cin >> n;
    vector<double> a(n), b(n);
    for (int i = 0; i < n; i++)
        cin >> a[i] >> b[i];
    double t = 0, ans = 0;
    for (int i = 0; i < n; i++)
    {
        t += a[i] / b[i];
    }
    t /= 2;
    for (int i = 0; i < n; i++)
    {
        ans += min(a[i], t * b[i]);
        t -= min(a[i] / b[i], t);
    }
    cout << fixed << setprecision(15);
    cout << ans << endl;
    return 0;
}
