#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

void solve(std::string S)
{

    vector<string> dic(S.size());
    for (int i = 0; i < S.size(); i++)
    {
        string s = S.substr(i, S.size()) + S.substr(0, i);
        dic[i] = (S.substr(i, S.size()) + S.substr(0, i));
    }

    sort(dic.begin(), dic.end());
    cout << dic.at(0) << endl;
    cout << dic.at(S.size() - 1) << endl;
}

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    std::string S;
    std::cin >> S;
    solve(S);
    return 0;
}
