#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
#define rep(i, n) for (int i = 0; i < (n); i++)

const string YES = "Yes";
const string NO = "No";

void solve(std::string S, std::string T)
{

    if (S == T)
    {
        cout << YES << endl;
        return;
    }

    rep(i, S.size() - 1)
    {
        string ns = S;
        swap(ns[i], ns[i + 1]);
        if (ns == T)
        {
            cout << YES << endl;
            return;
        }
    }
    cout << NO << endl;
    return;
}

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    std::string S;
    std::cin >> S;
    std::string T;
    std::cin >> T;
    solve(S, T);
    return 0;
}
