#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

/*
3点(x1, y1), (x2, y2), (x3, y3)の三環系の面積は、
2/1​∣(x2​−x1​)(y3​−y1​)−(x3​−x1​)(y2​−y1​)∣
であり。
値が０になる場合は３点が一直線上にある。
 */
// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long n;
    std::scanf("%lld", &n);
    vector<pair<long long, long long>> p(n);
    for (auto &nx : p)
    {
        cin >> nx.first >> nx.second;
    }
    int res = 0;
    for (int i = 0; i < n; i++)
    {
        for (int j = i + 1; j < n; j++)
        {
            for (int k = j + 1; k < n; k++)
            {
                if ((p[j].first - p[i].first) * (p[k].second - p[i].second) - (p[k].first - p[i].first) * (p[j].second - p[i].second) != 0)
                {
                    res++;
                }
            }
        }
    }
    cout << res << '\n';
}
