#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

const string YES = "Yes";
const string NO = "No";

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    // Failed to predict input format
    long long n, m;
    cin >> n >> m;

    bool check = true;
    int first;
    for (int i = 0; i < n; i++)
    {
        for (int j = 0; j < m; j++)
        {
            int value;
            cin >> value;
            int x, y;

            x = value % 7 + 1;
            y = value / 7;

            if (i == 0 && j == 0)
            {
                first = value;
            }
            if (value != first + 7 * i + j)
            {
                cout << value << endl;
                check = false;
            }
        }
    }

    cout << (check ? "Yes" : "No") << endl;

    return 0;
}
