#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
#define rep(i, n) for (int i = 0; i < (n); ++i)
const string YES = "Yes";
const string NO = "No";

/**
if (!(s[i] == 'x' || s[i] == 'o'))
        {
            cout << NO << endl;
            return;
        }
 */
// o → xx
// os → x
// oxx
// xox
// xxo
void solve(std::string s)
{
    /*
    do
    {
        for (int i = 0; i < 3; i++)
        {
            cout << s[i] << endl;
        }
    } while (next_permutation(s, s.size() + 3));
    */
}

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    std::string S;
    std::cin >> S;
    string t;
    rep(i, 10) t += "oxx";
    if (t.find(S) != string::npos)
    {
        cout << YES << endl;
    }
    else
    {
        cout << NO << endl;
    }
    return 0;
}
