#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

const string YES = "Yes";
const string NO = "No";

void solve(long long X)
{
    if (X < 100)
    {
        cout << NO << endl;
        return;
    }

    // 下2桁目
    if (X % 100 != 0)
    {

        cout << NO << endl;
        return;
    }

    cout << YES << endl;
}

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long X;
    std::scanf("%lld", &X);
    solve(X);
    return 0;
}
