#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

// Generated by 2.11.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    std::scanf("%lld", &N);
    std::vector<std::string> S(N);

    map<string, int> result;
    for (int i = 0; i < N; i++)
    {
        string input;
        std::cin >> input;
        if (result.count(input) == 1)
        {
            result[input] += 1;
        }
        else
        {
            result[input] = 1;
        }
    }

    string ans;
    int max = 0;

    for (auto itr = result.begin(); itr != result.end(); ++itr)
    {
        if (itr->second > max)
        {
            max = itr->second;
            ans = itr->first;
        }
        //::cout << "key = " << itr->first << ", val = " << itr->second << "\n";
    }
    cout << ans << endl;
    //    solve(N, std::move(S));
    return 0;
}
