#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
#define rep(i, n) for (int i = 0; i < (n); ++i)

void solve(long long n, long long a, long long b, long long p, long long q, long long r, long long s)
{
    int h = q - p + 1;
    int w = s - r + 1;

    vector<string> ans(h, string(w, '.'));

    rep(i, h) rep(j, w)
    {
        long long x = p + i, y = r + j;
        if (x - y == a - b || x + y == a + b)
        {
            ans[i][j] = '#';
        }
        rep(i, h) cout << ans[i] << endl;
    }
}

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long n, a, b;
    cin >> n >> a >> b;
    long long p, q, r, s;
    cin >> p >> q >> r >> s;

    int h = q - p + 1, w = s - r + 1;

    vector<string> ans(h, string(w, '.'));

    rep(i, h) rep(j, w)
    {
        long long x = p + i, y = r + j;
        if (x - y == a - b || x + y == a + b)
            ans[i][j] = '#';
    }

    rep(i, h) cout << ans[i] << endl;

    return 0;
}
